#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

case $USER in
  spencertipping)
  docker build -t spencertipping/ssh-base .
  docker build -t spencertipping/ssh-machine -f Dockerfile.spencer .
  docker push spencertipping/ssh-base
  docker push spencertipping/ssh-machine
  ;;

  joyce)
  docker build -t joycetipping/ssh-machine -f Dockerfile.joyce .
  docker push joycetipping/ssh-machine
  ;;
esac
