#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")"

case $USER in
  spencertipping)
  docker build -t spencertipping/ssh-base .
  docker build -t spencertipping/ssh-machine-minimal -f Dockerfile.spencer-minimal .
  docker build -t spencertipping/ssh-machine -f Dockerfile.spencer .

  docker build -t spencertipping/joyce-ssh-machine -f Dockerfile.joyce .

  for i in ssh-{base,machine{,-minimal}} joyce-ssh-machine; do
    docker tag spencertipping/$i registry.128:5000/$i
    docker push registry.128:5000/$i
  done
  ;;

  joyce)
  docker build -t joycetipping/ssh-machine -f Dockerfile.joyce .
  docker tag joycetipping/ssh-machine registry.128:5000/joyce-ssh-machine
  docker push registry.128:5000/joyce-ssh-machine
  ;;
esac
