#!/bin/bash
mkdir -p ~/.ssh
mv ~/$USER-id_rsa.pub ~/.ssh/authorized_keys

# TODO joyce: customize these to your setup
git clone https://github.com/spencertipping/dotfiles ~/dotfiles
git clone https://github.com/spencertipping/dotbash ~/.bash
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

# Initialize dotfiles
~/dotfiles/setup yes-really || :

source ~/.bash/init

stack setup

npm config set prefix ~/.npm-global
npm install -g npm
npm install -g purescript
npm install -g spago

emacs --batch --script ~/.emacs.d/init.el --kill
emacs --batch --script ~/.emacs.d/init.el --kill

rm "$0"
