#!/bin/bash
mkdir -p ~/.ssh
mv ~/$USER-id_rsa.pub ~/.ssh/authorized_keys

# TODO joyce: customize these to your setup
mkdir -p ~/projects

git clone https://github.com/joycetipping/configuration ~/projects/configuration
git clone https://github.com/spencertipping/dotbash ~/.bash
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

# Initialize dotfiles
~/projects/configuration/setup yes-really || :

cat > ~/passwords-edit <<'EOF'
#!/bin/bash
exec /mnt/jt/projects/passwords/edit
EOF

chmod +x ~/passwords-edit

source ~/.bash/init

rm "$0"
