#!/bin/bash
mkdir -p ~/.ssh ~/bin
mv ~/$USER-id_rsa.pub ~/.ssh/authorized_keys

[[ -d ~/r ]] || ln -s /mnt/v1/$USER ~/r

git clone https://github.com/spencertipping/dotfiles ~/dotfiles || exit $?
git clone https://github.com/spencertipping/dotbash ~/.bash     || exit $?

# Initialize dotfiles early
~/dotfiles/setup yes-really || :

source ~/.bash/init


# Conda + bashrc
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda || exit $?
rm Miniconda3-latest-Linux-x86_64.sh

eval "$(~/miniconda/bin/conda shell.bash hook)"
conda init || exit $?


# Remove this script so we don't rerun setup
cd
rm "$0"
