#!/bin/bash
mkdir -p ~/.ssh
mv ~/$USER-id_rsa.pub ~/.ssh/authorized_keys

[[ -d ~/r ]] || ln -s /mnt/v1/$USER ~/r

git clone https://github.com/spencertipping/dotfiles ~/dotfiles
git clone https://github.com/spencertipping/dotbash ~/.bash
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
  | bash - -b -p ~/miniconda

eval "$(~/miniconda/bin/conda shell.bash hook)"
conda init

conda install -y tensorflow


# Initialize dotfiles
~/dotfiles/setup yes-really || :

source ~/.bash/init

stack setup

npm config set prefix ~/.npm-global
npm install -g npm
npm install -g purescript
npm install -g spago

emacs --batch --script ~/.emacs.d/init.el --kill
emacs --batch --script ~/.emacs.d/init.el --kill

rm "$0"
