#!/bin/bash
mkdir -p ~/.ssh
mv ~/id_rsa.pub ~/.ssh/authorized_keys

[[ -d ~/r ]] || ln -s /mnt/v1/st ~/r

git clone https://github.com/spencertipping/dotfiles ~/dotfiles
git clone https://github.com/spencertipping/dotbash ~/.bash
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d

# Initialize dotfiles
~/dotfiles/setup yes-really

source ~/.bash/init

rm "$0"
